# nginx.conf - gestionado por deploy.ps1
# NO EDITAR DIRECTAMENTE EN EL SERVIDOR

worker_processes  auto;
error_log         "{{logPath}}/error.log" warn;
pid               "{{logPath}}/nginx.pid";

events {
    worker_connections  1024;
}

http {
    include       "{{installPath}}/conf/mime.types";
    default_type  application/octet-stream;

    access_log  "{{logPath}}/access.log";

    sendfile        on;
    tcp_nopush      on;
    keepalive_timeout  65;

    client_max_body_size 50m;

    server {
        listen       {{port}};
        server_name  _;

        root   "{{dataPath}}/www";
        index  index.html;

        location / {
            try_files $uri $uri/ =404;
        }
    }
}
